-- Creating triggers to populate primary keys using sequences

CREATE OR REPLACE TRIGGER FACTORY_TRG
    BEFORE INSERT ON FACTORY
    FOR EACH ROW
BEGIN
    IF :NEW.factory_id IS NULL THEN
        SELECT FACTORY_SEQ.NEXTVAL INTO :NEW.factory_id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER MACHINE_TRG
    BEFORE INSERT ON MACHINE
    FOR EACH ROW
BEGIN
    IF :NEW.machine_id IS NULL THEN
        SELECT MACHINE_SEQ.NEXTVAL INTO :NEW.machine_id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER WORKER_TRG
    BEFORE INSERT ON WORKER
    FOR EACH ROW
BEGIN
    IF :NEW.worker_id IS NULL THEN
        SELECT WORKER_SEQ.NEXTVAL INTO :NEW.worker_id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER PRODUCT_TRG
    BEFORE INSERT ON PRODUCT
    FOR EACH ROW
BEGIN
    IF :NEW.product_id IS NULL THEN
        SELECT PRODUCT_SEQ.NEXTVAL INTO :NEW.product_id FROM DUAL;
    END IF;
END;
/
